services:
  - type: web
    name: activepieces
    plan: starter
    env: docker
    image:
      url: ghcr.io/activepieces/activepieces:0.29.1
    autoDeploy: true
    envVars:
      - key: AP_POSTGRES_DATABASE
        fromDatabase:
          name: activepieces-postgres
          property: database
      - key: AP_POSTGRES_PASSWORD
        fromDatabase:
          name: activepieces-postgres
          property: password
      - key: AP_POSTGRES_USERNAME
        fromDatabase:
          name: activepieces-postgres
          property: user
      - key: REDIS_URL
        fromService:
          name: activepieces-redis
          type: redis
          property: connectionString
    healthCheckPath: /

  - type: redis
    name: activepieces-redis
    plan: starter
    ipAllowList: 
      - source: 0.0.0.0/0
        description: Allow all

databases:
  - name: activepieces-postgres
    plan: starter
    postgresMajorVersion: 14
    ipAllowList: 
      - source: 0.0.0.0/0
        description: Allow all

envVarGroups:
  - name: activepieces-env
    envVars:
      - key: AP_POSTGRES_DATABASE
        value: activepieces_db
      - key: AP_POSTGRES_PASSWORD
        value: yourpassword
      - key: AP_POSTGRES_USERNAME
        value: activepieces_user
