services:
  - type: web
    name: activepieces
    env: docker
    plan: starter
    image:
      url: ghcr.io/activepieces/activepieces:0.29.1
    dockerCommand: ""
    autoDeploy: true
    envVars:
      - key: AP_POSTGRES_DATABASE
        fromDatabase:
          name: activepieces-postgres
          property: database
      - key: AP_POSTGRES_PASSWORD
        fromDatabase:
          name: activepieces-postgres
          property: password
      - key: AP_POSTGRES_USERNAME
        fromDatabase:
          name: activepieces-postgres
          property: user
      - key: REDIS_URL
        fromService:
          name: activepieces-redis
          type: redis
          property: connectionString
    ports:
      - port: 8080
        targetPort: 80
    healthCheckPath: /

  - type: redis
    name: activepieces-redis
    plan: starter
    ipAllowList: 
      - source: 0.0.0.0/0
        description: Allow all

databases:
  - name: activepieces-postgres
    plan: starter
    postgresMajorVersion: 14
    databaseName: ${AP_POSTGRES_DATABASE}
    user: ${AP_POSTGRES_USERNAME}
    password: ${AP_POSTGRES_PASSWORD}
    ipAllowList: 
      - source: 0.0.0.0/0
        description: Allow all

envVarGroups:
  - name: activepieces-env
    envVars:
      - key: AP_POSTGRES_DATABASE
        sync: false
      - key: AP_POSTGRES_PASSWORD
        sync: false
      - key: AP_POSTGRES_USERNAME
        sync: false
